version: "3.4"
services:
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
  web:
    build:
      context: .
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - "3000:3000"
    links:
      - db
